### ISSUE TITLE
Roadmap v0.4.0

### ISSUE THREAD

**Issue by cyrildewit** [cyrildewit/laravel-accommodations#35]
### Secure

- [ ] Finish the login, register, and password reset functionality
- [ ] Add a user profile picture functionality
- [ ] Design the initial version of the secure environment (navigation)

### Management

- [ ] Build the login, register, and password reset functionality
- [ ] Add a user profile picture functionality
- [ ] Create an empty dashboard page
- [ ] Build the initial version of the listings index page
